### PR TITLE
Added error popups for configuration errors

### PR DESCRIPTION
**Pull request by newcomb-luke**
I added error popup windows for any place that we previously would just print to the terminal and process:exit().

alarm_error_popup

### CODE REVIEW

**Comment by newcomb-luke** [comment]
Tested and it works on Windows too.

image

**Comment by HernanW4** [comment]
You have a clippy warning at the ball.rs file. It seems like when you make the random velocity variable you do an unnecessary cast type.

**Review by HernanW4 — CHANGES_REQUESTED** [review]
Fix the Clippy warning, remove the `as f32` in line 79 on ball.rs

**Comment by newcomb-luke** [comment]
> Fix the Clippy warning, remove the `as f32` in line 79 on ball.rs

Fixed.

**Review by HernanW4 — APPROVED** [review]
Beautiful, :)

**Pull request merged**
